config/routes.rb
Rails.application.routes.draw do
  resources :announcements do
    resources :comments
  end
  root 'announcements#main_page'

  get 'index' => 'announcements#index'
  get 'main_page' => 'announcements#main_page'
  #get 'show' => 'announcements#show'
  get '/announcements/show/:id' => 'announcements#show', as: 'show'



end

app/models/announcement.rb
class Announcement < ApplicationRecord
  has_many :comments, dependent: :destroy
  before_create :set_time_creation
  default_scope {order(publicationDate:'DESC')}
  validates :headline, :presence => true
  validates :subhead, :presence => true
  validates :body, :presence => true
  validates_length_of :subhead, :maximum => 250, :too_long =>"the subhead is too long, maximum is 250 chars"
  def subhead_lenght
  end
  def set_time_creation
    self.publicationDate = Time.now
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :announcement
  validates :name, :presence => true
  validates :body, :presence => true
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all
  end

  def indexadmin
    @mainannouncements = Announcement.take(10)
  end
  helper_method :indexadmin
  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end


  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:headline, :subhead, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @announcement = Announcement.find(params[:announcement_id])
    @comment = @announcement.comments.create(params[:comment].permit(:name, :body))
    redirect_to announcement_path(@announcement)
  end
  def destroy
    @announcement = Announcement.find(params[:announcement_id])
    @comment = @announcement.comments.find(params[:id])
    @comment.destroy
    redirect_to announcement_path(@announcement)
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/announcements/_form.html.erb
<%= form_for(announcement) do |f| %>
  <% if announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :headline %>
    <%= f.text_field :headline %>
  </div>

  <div class="field">
    <%= f.label :subhead %>
    <%= f.text_field :subhead %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', href='/main_page' %>

app/views/announcements/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
    <h1>The Newspaper</h1>
    <p>A little page to read all the important news.</p>
</div>
<div>
  <h1>
      <span class="label label-info pull-left" ><%= link_to 'New Announcement', new_announcement_path %></span>
  </h1>
  <h1>
    <a href='/main_page' button type="button" class="btn btn-lg btn-success pull-right" > Back home</a>
  </h1>
<br>
<br>

         <table class="table table-striped">
           <thead>
             <tr>
               <th><h3>Publication date</h3></th>
               <th><h3>Headline</h3></th>
               <th colspan="3"></th>
             </tr>
           </thead>
           <tbody>
             <% @announcements.each do |announcement| %>
               <tr>
                 <td><%= announcement.publicationDate %></td>
                 <td><%= announcement.headline %></td>
                 <td><h2><span class="label label-info"><%= link_to 'Show', announcement %></span></h2></td>
                 <td><h2><span class="label label-info"><%= link_to 'Edit', edit_announcement_path(announcement) %></span></h2></td>
                 <td><h2><span class="label label-info"><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></span></h2></td>
               </tr>
             <% end %>
           </tbody>
         </table>
       </div>
     </div>
<br>
<h1>
  <a href='/main_page' button type="button" class="btn btn-lg btn-success pull-right" > Back home</a>
</h1>
<br>
<br>

app/views/announcements/main_page.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
    <h1>The Newspaper</h1>
    <p>A little page to read all the important news.</p>
    <a href='/index' button type="button" class="btn btn-lg btn-info pull-right" > admin</a>
</div>
<% indexadmin.each do |announcement| %>
    <div class="panel panel-info">
               <div class="panel-heading">
                 <h3><%= announcement.headline %></h3>
               </div>
               <div class="panel-body">
              <a href="<%= show_path(announcement.id) %>" class="list-group-item">
              <h4 class="list-group-item-heading"><%= announcement.subhead %></h4>
              <p class="list-group-item-text"><%= announcement.body[0,1000] %></p>
            </a>
               </div>
               <div align="left"> <%= announcement.comments.count %> Comments</div>
               <div align="right"><%= announcement.publicationDate %></div>
    </div>
<% end %>
           </tbody>
         </table>

app/views/announcements/new.html.erb
<h1>New Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Publicationdate:</strong>
  <%= @announcement.publicationDate %>
</p>

<p>
  <strong>Headline:</strong>
  <%= @announcement.headline %>
</p>

<p>
  <strong>Subhead:</strong>
  <%= @announcement.subhead %>
</p>

<p>
  <strong>Body:</strong>
  <%= @announcement.body %>
</p>

<% @announcement.comments.each do |comments| %>
    <div class="panel panel-info">
               <div class="panel-heading">
                 <h4><%= comments.name %></h4>
               </div>
               <div class="panel-body">
              <p class="list-group-item-text"><%= comments.body %></p>
              <p align="right"><%= link_to 'Delete', [comments.announcement, comments], method: :delete, data: {confirm:'Are you sure?'}%> </p>
            </a>
               </div>
    </div>
<% end %>

      <h3> Add a Comment: </h3>
      <%= render 'comments/form' %>
<br>

<%= link_to 'Back', href='/main_page' %>

app/views/comments/_comment.html.erb
<p><%= comment.name %></p>
<p><%= comment.body %></p>

<p><%= link_to 'Delete', [comment.announcement, comment], method: :delete, data: {confirm:'Are you sure?'}%> </p>

app/views/comments/_form.html.erb
<%= form_for([@announcement,@announcement.comments.build]) do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheNewspaper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>